version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - secretnet
  secretlink-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      CRYPTO_SECRET_KEY: aBcDeFgHiJkLmNoPqRsTuVwXyZ123456
      CLEANUP_TASK_RATE: 3000
    ports:
      - "8080:8080"
    networks:
      - secretnet
    depends_on:
      - db

  secretlink-frontend:
    image: secretlink-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - secretlink-backend
    networks:
      - secretnet

networks:
  secretnet:
